#!/bin/bash

WORKTREE_DIR=/home/fraimondo/dev/projects/julearn

while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received.  Deploying master branch to production..."
        git --work-tree=$WORKTREE_DIR --git-dir=$GIT_DIR checkout -f
    else
        echo "Ref $ref successfully received.  Doing nothing: only the master branch may be deployed on this server."
    fi
done
